name: setup

description: Setup Node, cache and install deps

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup git user
      shell: bash
      run: |
        git config --global user.name '@qwikifiers'
        git config --global user.email 'qwik-nx@users.noreply.github.com'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.7.0

    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Nx set SHAs
      uses: nrwl/nx-set-shas@v3.0.1
      id: setSHAs
      with:
        main-branch-name: 'main'
